### ISSUE TITLE
Structural Issues Tracker

### ISSUE THREAD

**Issue by malramsay64** [malramsay64/phd-thesis#229]
This tracks structural issues raised in the review of my thesis. There are a number of specific issues raised, which are listed below, although this will also track other structural changes that may not have been explicitly raised.

- [x] The Methods chapter comes after the Conclusions chapter. (30d60b8)
- [x] Few references to methods chapter
- [x] Forward referencing of results and figures
