### ISSUE TITLE
Language Issue Tracker

### ISSUE THREAD

**Issue by malramsay64** [malramsay64/phd-thesis#230]
This highlights some of the language issues presented through the review of my thesis. This will reference all the changes that concern language.

### Sentence fragments

- [x] “. close to the glass transition temperature.” on p.6,
- [x] “is millisecond timescales Chemos and colleagues” on p.8,
- [x] “While the ... relaxation” on p. 13,
- [x] “In experimental systems ...” on p.17, etc.),

### Sentences omitting punctuation

- [x] “These tools describe the motions of individual molecules providing a link between local environments and dynamics.” on p. 10,
- [x] “the size of the energy barriers ... which take place” on p. 37, etc.,

### Incorrect subject-verb agreement

- [x] “The viscosity ... are shown” on p. 1,
- [x] “there are still issue running simulations” on p. 9,
- [x] “the displacements ... is” on p. 48),

### Its

- [x] “its” almost university misspelt “it’s”,

### Rhetorical questions without question marks

- [x] “Are the dynamics ...” on p. 48,

### Other mistakes

- [x] “to measure contribution” on p. 33,
- [x] “exampling the coupling” on p. 39,
- [x] “corresponding the first peak” on p. 40,
- [x] SED is introduced as an abbreviation on p. 34 before it is defined on p. 37
- [x] Sentences starting with references to figures or sections do so uncapitalised.

### Consistency of tense in descriptions of the literature

- [ ] what others “find” or “found”

### Informal and ambiguous language

- [x] “phenomenally slow crystal growth rates” on p. 1,
- [x] “Part of the issue ...” on p. 8,
- [x] "A year later they follow up ...” on p. 9,
- [x] “while coloured areas have lots of motion.” on p. 27,
- [x] “The rotational diffusion speeds up relative to the translational diffusion at a given termperaure”, on p. 31,
- [x] “satisfy some proportionality criteria” on p 47, etc.
